/**
 * Touched-surface audit — generated by pre-pr-ui-audit.
 *
 * Reads the surface manifest produced by resolve-surfaces.mjs and, for every
 * surface x width x state, runs axe-core AND the geometric probes axe cannot
 * express. Copy into changemaker-gcp as
 * `tests/e2e/accessibility/<TICKET>-touched-surfaces.a11y.spec.ts` — the
 * `accessibility` Playwright project matches `**\/*.a11y.spec.ts`.
 *
 *   AUDIT_MANIFEST=.audit/surfaces.json pnpm playwright test --project=accessibility
 *
 * Why this is not another route-list sweep: the route list comes from the diff,
 * the widths come from the diff's own breakpoint prefixes, and a surface marked
 * `opens` or `seeds` is driven into that state before anything is measured.
 */

import AxeBuilder from '@axe-core/playwright'
import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { credentials } from '../../config/credentials'
import { loginWithCredentials } from '../support/auth'
import { runProbes, settle, type Finding } from './probes'

const MANIFEST = process.env.AUDIT_MANIFEST || '.audit/surfaces.json'
const WORKSPACE = process.env.A11Y_WORKSPACE_SLUG || 'alldigitalrewards'
const WCAG_TAGS = ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa']

interface Surface {
  route: string
  role: keyof typeof ROLE_EMAIL
  depth: number
  widths: number[]
  opens: string[]
  seeds: string[]
  reason: { file: string; depth: number }[]
}

const ROLE_EMAIL = {
  platformAdmin: credentials.platformAdmin.email,
  admin: credentials.workspaceAdmin.email,
  manager: credentials.manager.email,
  participant: credentials.participant.email,
  client: credentials.clientViewer.email,
  public: '',
} as const

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'))
const surfaces: Surface[] = manifest.surfaces

/**
 * Dynamic segments are resolved once against the seeded workspace. An
 * unresolved segment is a hard failure, not a skip — a silently skipped
 * `[id]` route is the shape of "the gate was green and QA still found it".
 */
async function resolveRoute(page: Page, route: string): Promise<string | null> {
  let path = route.replace(/\[slug\]/g, WORKSPACE)
  if (!path.includes('[')) return path

  if (/\[id\]|\[challengeId\]/.test(path)) {
    const res = await page.request.get(`/api/workspaces/${WORKSPACE}/challenges`)
    const id = (await res.json().catch(() => ({})))?.challenges?.[0]?.id
    if (!id) return null
    path = path.replace(/\[id\]|\[challengeId\]/g, id)
  }
  if (path.includes('[workspaceId]')) {
    const res = await page.request.get('/api/admin/workspaces')
    const id = (await res.json().catch(() => ({})))?.workspaces?.[0]?.id
    if (!id) return null
    path = path.replace(/\[workspaceId\]/g, id)
  }
  return path.includes('[') ? null : path
}

/**
 * Open every overlay the surface owns and probe each one.
 *
 * This is the state a `goto`-only sweep cannot reach. DS-13634's failing step
 * indicator lived inside the Create Workspace dialog: the route was scanned,
 * the dialog was never opened, the gate reported zero violations, and QA found
 * three sub-AA pills.
 */
const DESTRUCTIVE = /delete|remove|deactivate|archive|sign ?out|log ?out|send|submit|save|confirm|publish|invite/i

async function openOverlay(page: Page): Promise<string | null> {
  const triggers = page.locator('button:visible, [role="button"]:visible')
  const count = Math.min(await triggers.count(), 12)
  for (let i = 0; i < count; i++) {
    const trigger = triggers.nth(i)
    const name = ((await trigger.textContent()) || '').trim().slice(0, 40)
    // Never click anything that mutates state or navigates away — an audit
    // must not be able to change the data it is auditing.
    if (!name || DESTRUCTIVE.test(name)) continue
    await trigger.click({ timeout: 2000 }).catch(() => {})
    const overlay = page.locator('[role="dialog"]:visible, [role="menu"]:visible, [role="listbox"]:visible')
    if (await overlay.count()) return name
  }
  return null
}

function format(f: Finding, ctx: string): string {
  const m = Object.entries(f.measured)
    .map(([k, v]) => `${k}=${v}`)
    .join(' ')
  return `  [${f.probe}] ${f.wcag ?? ''} ${ctx}\n    ${f.selector}\n    "${f.text}"\n    ${f.detail}\n    ${m}`
}

test.describe('Touched-surface WCAG + reflow audit', () => {
  test.describe.configure({ mode: 'serial' })

  for (const surface of surfaces) {
    const email = ROLE_EMAIL[surface.role]

    test(`${surface.role} ${surface.route}`, async ({ page }) => {
      test.skip(!email && surface.role !== 'public', `No credential configured for role ${surface.role}`)
      test.setTimeout(120_000 + surface.widths.length * 20_000)

      if (email) await loginWithCredentials(page, email)

      const path = await resolveRoute(page, surface.route)
      // A route we cannot resolve is reported, never quietly passed.
      expect(path, `could not resolve dynamic segments in ${surface.route} — seed the workspace or resolve by hand`).not.toBeNull()

      const failures: string[] = []

      for (const width of surface.widths) {
        await page.setViewportSize({ width, height: width < 768 ? 812 : 1000 })
        await page.goto(path!, { waitUntil: 'domcontentloaded' })
        await settle(page)

        const axe = await new AxeBuilder({ page }).withTags(WCAG_TAGS).analyze()
        for (const v of axe.violations) {
          failures.push(
            `  [axe:${v.id}] ${v.impact} @${width}px — ${v.nodes.length} node(s)\n    ${v.nodes
              .slice(0, 3)
              .map((n) => n.target.join(' '))
              .join('\n    ')}`
          )
        }
        // axe reports gradient-backed text as *incomplete*, never a violation.
        // Surface those rather than dropping them.
        for (const inc of axe.incomplete.filter((i) => i.id === 'color-contrast')) {
          failures.push(
            `  [axe-incomplete:color-contrast] @${width}px — ${inc.nodes.length} node(s) axe could not resolve ` +
              `(gradient or translucent backdrop). Verify with ${'challenge-contrast.spec.ts'}'s walker.\n    ` +
              inc.nodes.slice(0, 3).map((n) => n.target.join(' ')).join('\n    ')
          )
        }

        for (const f of await runProbes(page)) failures.push(format(f, `@${width}px`))

        // The overlay pass — only where the diff put an overlay on this surface.
        if (surface.opens.length) {
          const opened = await openOverlay(page)
          if (opened) {
            await settle(page)
            const overlayAxe = await new AxeBuilder({ page }).withTags(WCAG_TAGS).analyze()
            for (const v of overlayAxe.violations) {
              failures.push(`  [axe:${v.id}] ${v.impact} @${width}px in overlay "${opened}" — ${v.nodes.length} node(s)`)
            }
            for (const f of await runProbes(page)) failures.push(format(f, `@${width}px in overlay "${opened}"`))
            await page.keyboard.press('Escape').catch(() => {})
          } else {
            failures.push(
              `  [coverage] @${width}px — this surface's diff contains an overlay but the audit could not open one. ` +
                `Drive it by hand before claiming coverage.`
            )
          }
        }
      }

      // A data-gated surface has two trees and a goto only ever renders one.
      // Refusing to pass silently is the whole point: DS-13634's 1.72:1 badge
      // was invisible to a green gate purely because the queue was empty.
      if (surface.seeds.length && !process.env.AUDIT_SEEDED) {
        failures.push(
          `  [coverage] this surface renders conditionally on data (${surface.seeds.join(', ')}). ` +
            `Seed it with tests/helpers/factories so the populated branch renders, re-run with ` +
            `AUDIT_SEEDED=1, and only then read the result as covering both arms.`
        )
      }

      const unique = [...new Set(failures)]
      expect(
        unique,
        `\n${surface.role} ${surface.route}\nchanged by: ${surface.reason.map((r) => r.file).join(', ')}\n\n${unique.join('\n\n')}\n`
      ).toEqual([])
    })
  }
})

/**
 * Surfaces marked `seeds` render a different tree when their data is non-empty.
 * DS-13634's amber Submissions count badge (1.72:1) only paints when the review
 * queue has entries, so the 40-route sweep never rendered the failing node at
 * all. This spec drives whatever state the workspace happens to be in; when a
 * surface is marked `seeds`, seed it first and re-run, or the pass is partial.
 *
 * The manifest carries the flag rather than the seeding, because seeding is
 * repo-specific — use tests/helpers/factories.
 */
